### ISSUE TITLE
Citation Guidelines for Bilayers

### ISSUE THREAD

**Issue by rajavishah** [bilayer-containers/bilayers#32]
We need to determine how users should cite Bilayers. Initially, we considered using a DOIs array in the spec file. 
Adding DOIs should be needed for wrapper and the wrapped tool.  

### Key Points - How to find Citations:

1. Check for CITATION Files:
   - First, look in the GitHub repository for `CITATION`, `CITATION.md`, or `CITATION.cff` files to find citation information of any tool.

2. Published Papers:
   - If the tool has a published paper, link to it for citation. These can often be found in the GitHub repo or through a quick search.

3. Citing Interfaces:
   - Ensure that interfaces, like Jupyter or Gradio, are also cited. Refer to their respective `CITATION.cff` files or other citation guidelines provided.

4. Zenodo Archiving:
   - If no published paper exists, check if the repository has been archived on Zenodo, which generates a DOI for citation purposes. This is less common but worth checking.

### Key Points - How to attach citations at `config.yaml` level?

1. Along with DOIs, we want to put a one-liner description. We would put everything under citations:
```
citations:
      Jupyter:
         - name: "Jupyter"
           doi: 10.1109/MCSE.2007.53
           description: "Interactive, code-driven documents for data analysis and visualization"

      Gradio:
         - name: "Gradio"
           doi: 10.48550/arXiv.1906.02569
           description: "A simple web interface for deploying machine learning models"

      Algorithm: 
         - name: "Cellpose"
            doi: 10.1038/s41592-020-01018-x
            description: "Deep Learning algorithm for cell segmentation in microscopy images"
```
